/**
 * India Land Information Portal - GIS Resource Catalog
 * All 32 curated datasets across Satellite Imagery, Elevation/Roads, Population/Socioeconomic,
 * Land Records, and Geospatial Modeling Tools.
 */
const resourceDatabase = [
  // 01 Satellite Imagery (12)
  {
    id: "res_copernicus_data_space",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "Copernicus Data Space Ecosystem",
    provider: "European Space Agency (ESA) / EU",
    url: "https://dataspace.copernicus.eu/",
    accessType: "Free with Registration",
    apiAvailable: true,
    status: "Available",
    coverage: "Global / India 10m - 60m",
    temporalResolution: "5-day revisit (Sentinel-2)",
    formats: ["SAFE", "GeoTIFF", "Cloud-Optimized GeoTIFF (COG)", "STAC API"],
    description: "The primary portal for accessing open Sentinel-1, Sentinel-2, Sentinel-3, and Sentinel-5P satellite data. Provides on-demand processing, STAC catalogs, and JupyterLab cloud environments for land monitoring.",
    bestFor: "Vegetation index time-series (NDVI), multispectral land cover classification, and flood extent mapping.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_copernicus_browser",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "Copernicus Browser (Sentinel Hub)",
    provider: "ESA / Planet Labs",
    url: "https://browser.dataspace.copernicus.eu/",
    accessType: "Free / No Login for Preview",
    apiAvailable: true,
    status: "Available",
    coverage: "Global / Pan-India",
    temporalResolution: "Real-time updates",
    formats: ["GeoTIFF", "PNG/JPEG", "KMZ", "WMS/WMTS/WFS"],
    description: "Interactive visual search and analysis browser for multi-mission satellite imagery. Enables rapid comparison of false-color composites, NDVI, moisture index, and custom script evaluations over Indian states.",
    bestFor: "Visual inspection, split-screen temporal comparison, and instant spectral index visualization.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_sentinel2_docs",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "Sentinel-2 Mission & Dataset Technical Docs",
    provider: "Copernicus Space Component",
    url: "https://documentation.dataspace.copernicus.eu/Data/SentinelMissions/Sentinel2.html",
    accessType: "Open Access Docs",
    apiAvailable: false,
    status: "Available",
    coverage: "Global Technical Specs",
    temporalResolution: "Mission Lifetime (2015-present)",
    formats: ["Documentation", "Band Specifications", "Processing Baselines"],
    description: "Comprehensive scientific documentation for Sentinel-2 Level-1C (top-of-atmosphere) and Level-2A (bottom-of-atmosphere surface reflectance) data products with 13 spectral bands.",
    bestFor: "Band wavelength calculations, atmospheric correction pipelines, and radiometric calibration.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_google_earth_engine",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "Google Earth Engine (GEE) Platform",
    provider: "Google",
    url: "https://earthengine.google.com/",
    accessType: "Free for Research & Non-Commercial",
    apiAvailable: true,
    status: "Available",
    coverage: "Global Petabyte-scale Catalog",
    temporalResolution: "1972 to present (Landsat to Sentinel)",
    formats: ["Cloud Asset", "GeoTIFF", "NumPy Array", "GeoJSON"],
    description: "Planetary-scale platform for Earth science data & analysis. Combines a multi-petabyte catalog of satellite imagery with geospatial analysis capabilities powered by Google Cloud infrastructure.",
    bestFor: "Large-scale state-level land cover mapping, time-series anomaly detection, and cloud computing.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_gee_python_api",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "GEE Python API & geemap Guides",
    provider: "Google Earth Engine Community",
    url: "https://developers.google.com/earth-engine/guides/python_install",
    accessType: "Open Source SDK",
    apiAvailable: true,
    status: "Available",
    coverage: "Developer Ecosystem",
    temporalResolution: "Continuous updates",
    formats: ["Python Library (ee)", "Jupyter Notebooks", "REST API"],
    description: "Official guide and setup instructions for the Python client library for Google Earth Engine. Pairs seamlessly with `geemap` for interactive mapping in Jupyter environments.",
    bestFor: "Automated batch processing of Indian state mosaics and custom machine learning pipelines.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_esa_worldcover_viewer",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "ESA WorldCover Global Land Cover Viewer",
    provider: "European Space Agency / VITO Remote Sensing",
    url: "https://esa-worldcover.org/en",
    accessType: "Free Public Web Viewer",
    apiAvailable: true,
    status: "Available",
    coverage: "Global 10m Resolution",
    temporalResolution: "Annual (2020, 2021+)",
    formats: ["Cloud-Optimized GeoTIFF", "Map Tiles (WMS)", "VRT"],
    description: "High-resolution 10-meter global land cover product providing 11 land cover classes (Tree cover, Shrubland, Grassland, Cropland, Built-up, Bare / sparse vegetation, Snow and ice, Permanent water bodies, Herbaceous wetland, Mangroves, Moss and lichen).",
    bestFor: "Baseline land cover classification validation and urban-rural boundary delineation.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_esa_worldcover_data",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "ESA WorldCover Data Download & API Access",
    provider: "ESA / VITO",
    url: "https://esa-worldcover.org/en/data-access",
    accessType: "Free Open Data (CC BY 4.0)",
    apiAvailable: true,
    status: "Available",
    coverage: "Pan-India 3x3 degree tiles",
    temporalResolution: "Annual products",
    formats: ["GeoTIFF", "AWS S3 / Zenodo direct download"],
    description: "Direct download portal and cloud access endpoints for ESA WorldCover tiles covering the entire Indian subcontinent with high validation accuracy.",
    bestFor: "Downloading GeoTIFF rasters for state GIS offline analysis in QGIS and ArcGIS.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_esa_worldcover_aws",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "ESA WorldCover on AWS Open Data Registry",
    provider: "Amazon Web Services / VITO",
    url: "https://registry.opendata.aws/esa-worldcover-vito/",
    accessType: "Open Data Cloud Bucket",
    apiAvailable: true,
    status: "Available",
    coverage: "Global S3 Bucket",
    temporalResolution: "Annual",
    formats: ["S3 Cloud-Optimized GeoTIFF (COG)"],
    description: "Cloud-native access to WorldCover data hosted on AWS S3 (`s3://esa-worldcover`). Enables streaming spatial queries without downloading full multi-gigabyte rasters.",
    bestFor: "Direct raster window queries with GDAL, Rasterio, and STAC API clients.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_bhuvan_isro",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "ISRO Bhuvan Indian Geo-Platform",
    provider: "National Remote Sensing Centre (NRSC) / ISRO",
    url: "https://bhuvan.nrsc.gov.in/",
    accessType: "Free Government Portal",
    apiAvailable: true,
    status: "Available",
    coverage: "India & South Asia (High Resolution)",
    temporalResolution: "IRS/Cartosat/Resourcesat series",
    formats: ["WMS/WFS/WMTS", "KML", "Shapefile", "GeoTIFF"],
    description: "The national Geo-portal developed by ISRO, hosting multi-resolution satellite imagery (Resourcesat, Cartosat, Oceansat) and rich thematic services for Indian geography, natural resources, and disasters.",
    bestFor: "Official Indian administrative boundaries, state thematic mapping, and disaster management overlays.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_bhuvan_lulc",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "Bhuvan Thematic LULC (Land Use / Land Cover)",
    provider: "NRSC / ISRO",
    url: "https://bhuvan-app1.nrsc.gov.in/thematic/",
    accessType: "Free Interactive GIS Viewer",
    apiAvailable: true,
    status: "Available",
    coverage: "Pan-India (1:50,000 & 1:250,000)",
    temporalResolution: "Multi-year thematic cycles",
    formats: ["Thematic Vector/Raster", "Statistical Tables"],
    description: "Authoritative national Land Use and Land Cover (LULC) dataset mapped at 1:50,000 scale by ISRO, capturing wasteland classification, wetland inventories, water bodies, and forest types across Indian districts.",
    bestFor: "Official government land-use statistics, net sown area verification, and wasteland mapping.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_bhuvan_free_data",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "Bhuvan Free Satellite Data & DEM Download",
    provider: "NRSC / ISRO",
    url: "https://bhuvan.nrsc.gov.in/wiki/index.php/Free_Satellite_Data_Download",
    accessType: "Free Registration Required",
    apiAvailable: true,
    status: "Available",
    coverage: "Pan-India & Oceans",
    temporalResolution: "Historical to Current",
    formats: ["CartoDEM (30m)", "Resourcesat AWiFS/LISS-III", "Oceansat OCM"],
    description: "ISRO's data distribution service offering free Cartosat Digital Elevation Models (CartoDEM 30m resolution), AWiFS (56m), and LISS-III imagery over India.",
    bestFor: "Indian terrain analysis, slope modeling, and watershed catchment boundary delineation.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_dynamic_world",
    category: "01_Satellite_Imagery",
    categoryName: "Satellite Imagery & Earth Observation",
    name: "Google Dynamic World (Near Real-Time LULC)",
    provider: "World Resources Institute (WRI) & Google",
    url: "https://dynamicworld.app/",
    accessType: "Free Open Access",
    apiAvailable: true,
    status: "Available",
    coverage: "Global 10m Resolution",
    temporalResolution: "Near Real-Time (Every Sentinel-2 pass)",
    formats: ["GEE Image Collection", "GeoTIFF", "Probability Vectors"],
    description: "Deep learning-driven 10-meter near real-time land use land cover dataset produced continuously from Sentinel-2 imagery with 9 class probabilities.",
    bestFor: "Tracking ongoing construction, seasonal water fluctuations, and rapid crop cycle transitions.",
    lastChecked: "2026-08-20"
  },

  // 02 Elevation, Roads, Boundaries (6)
  {
    id: "res_srtm_dem_gee",
    category: "02_Elevation_Roads_Boundaries",
    categoryName: "Elevation, Roads & Administrative Boundaries",
    name: "NASA SRTM Digital Elevation 30m Dataset",
    provider: "NASA JPL / USGS / GEE",
    url: "https://developers.google.com/earth-engine/datasets/catalog/USGS_SRTMGL1_003",
    accessType: "Open Public Domain",
    apiAvailable: true,
    status: "Available",
    coverage: "Global 1 arc-second (~30m)",
    temporalResolution: "Feb 2000 Baseline",
    formats: ["GeoTIFF", "Earth Engine Asset", "HGT"],
    description: "Shuttle Radar Topography Mission (SRTM) global digital elevation model providing void-filled elevation data at 1 arc-second (30 meters) resolution.",
    bestFor: "Slope, aspect, hillshade, topographic contour generation, and site suitability models.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_openstreetmap",
    category: "02_Elevation_Roads_Boundaries",
    categoryName: "Elevation, Roads & Administrative Boundaries",
    name: "OpenStreetMap (OSM) India Vector Data",
    provider: "OpenStreetMap Foundation (OSMF)",
    url: "https://www.openstreetmap.org/",
    accessType: "Open Data (ODbL)",
    apiAvailable: true,
    status: "Available",
    coverage: "Pan-India Complete Vector Stack",
    temporalResolution: "Live crowd-sourced community edits",
    formats: ["PBF", "XML", "GeoJSON", "Shapefile"],
    description: "The world's most comprehensive collaborative map database. Contains detailed road networks (National Highways, State Highways, village roads), building footprints, railway lines, and points of interest across India.",
    bestFor: "Infrastructure accessibility routing, urban density analysis, and road buffer zoning.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_overpass_api",
    category: "02_Elevation_Roads_Boundaries",
    categoryName: "Elevation, Roads & Administrative Boundaries",
    name: "Overpass API (OSM Data Extractor Engine)",
    provider: "OpenStreetMap Community",
    url: "https://overpass-api.de/",
    accessType: "Free High-Speed Query API",
    apiAvailable: true,
    status: "Available",
    coverage: "Global / India Geofenced Queries",
    temporalResolution: "Minutely synced",
    formats: ["GeoJSON", "OSM XML", "JSON", "CSV"],
    description: "Read-only API that serves up custom selected parts of the OSM map data. Optimized for querying specific features (e.g., all hospitals, substations, or schools in a state) via Overpass QL.",
    bestFor: "Extracting specific infrastructure vectors for site suitability and proximity analysis.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_overpass_turbo",
    category: "02_Elevation_Roads_Boundaries",
    categoryName: "Elevation, Roads & Administrative Boundaries",
    name: "Overpass Turbo (Interactive Query Sandbox)",
    provider: "Martin Raifer / OSM",
    url: "https://overpass-turbo.eu/",
    accessType: "Free Web Sandbox",
    apiAvailable: false,
    status: "Available",
    coverage: "Interactive Canvas with Map Preview",
    temporalResolution: "Real-time query execution",
    formats: ["Interactive Map", "GeoJSON Export", "KML", "GPX"],
    description: "A web-based data mining tool for OpenStreetMap. Allows users to write spatial queries, execute them, visualize the results on a Leaflet map, and download the GeoJSON vector files.",
    bestFor: "Visual query prototyping, rapid feature extraction, and bounding box exports.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_gadm_boundaries",
    category: "02_Elevation_Roads_Boundaries",
    categoryName: "Elevation, Roads & Administrative Boundaries",
    name: "GADM Database of Global Administrative Areas",
    provider: "University of California, Davis",
    url: "https://gadm.org/",
    accessType: "Free for Academic & Non-Commercial Use",
    apiAvailable: true,
    status: "Available",
    coverage: "India Admin Levels 0 (Country), 1 (State), 2 (District), 3 (Taluk/Tehsil)",
    temporalResolution: "Periodic boundary updates",
    formats: ["GeoPackage", "Shapefile", "R spatial (rds)", "KMZ"],
    description: "High-resolution spatial database of the world's administrative boundaries. Provides detailed multi-level vector polygons for all Indian states, union territories, districts, and subdivisions.",
    bestFor: "Administrative boundary clipping, choropleth map generation, and regional aggregation.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_survey_of_india",
    category: "02_Elevation_Roads_Boundaries",
    categoryName: "Elevation, Roads & Administrative Boundaries",
    name: "Survey of India (SOI) Official Geoportal",
    provider: "Survey of India / Department of Science & Technology (DST)",
    url: "https://surveyofindia.gov.in/",
    accessType: "Official Government Portal",
    apiAvailable: true,
    status: "Available",
    coverage: "Official Sovereign National Geodetic Network",
    temporalResolution: "Open Series Maps (OSM 1:50,000)",
    formats: ["PDF Toposheets", "WMS / Sarthi Geospatial Services", "DEM"],
    description: "The National Survey and Mapping Organization of India. Source of official international boundaries, state borders, topographical Open Series Maps (OSM), and the CORS (Continuously Operating Reference Stations) network.",
    bestFor: "Authoritative sovereign boundary alignment and legal geospatial reference frames.",
    lastChecked: "2026-08-20"
  },

  // 03 Population, Socioeconomic (5)
  {
    id: "res_census_india",
    category: "03_Population_Socioeconomic",
    categoryName: "Population, Demographics & Socio-Economic",
    name: "Census of India Official Portal",
    provider: "Office of the Registrar General & Census Commissioner, India",
    url: "https://censusindia.gov.in/",
    accessType: "Free Government Public Domain",
    apiAvailable: false,
    status: "Available",
    coverage: "Pan-India National / State / District / Village Level",
    temporalResolution: "Decennial Baseline + Projections",
    formats: ["XLSX", "CSV", "PDF Tables", "District Census Handbooks (DCHB)"],
    description: "Primary repository for official demographic data in India, encompassing total population, gender ratio, literacy, household amenities, worker classifications, and Primary Census Abstracts (PCA).",
    bestFor: "Ground-truth demographic baselines and state-level socioeconomic indicator cross-validation.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_census_data_portal",
    category: "03_Population_Socioeconomic",
    categoryName: "Population, Demographics & Socio-Economic",
    name: "Census Open Data Catalog (Data.gov.in)",
    provider: "Open Government Data (OGD) Platform India / NIC",
    url: "https://www.data.gov.in/catalog/all-india-census",
    accessType: "Open Government Data (API & CSV)",
    apiAvailable: true,
    status: "Available",
    coverage: "State & District Level Machine-Readable Datasets",
    temporalResolution: "Structured catalogs",
    formats: ["JSON API", "CSV", "XML", "ODS"],
    description: "Machine-readable open datasets from Census of India published under the National Data Sharing and Accessibility Policy (NDSAP). Offers REST APIs for programmatic demographic analysis.",
    bestFor: "Automated API ingestion into web dashboards, charts, and spatial statistical packages.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_worldpop",
    category: "03_Population_Socioeconomic",
    categoryName: "Population, Demographics & Socio-Economic",
    name: "WorldPop Gridded Population Density (100m)",
    provider: "WorldPop / University of Southampton",
    url: "https://www.worldpop.org/",
    accessType: "Open Access (CC BY 4.0)",
    apiAvailable: true,
    status: "Available",
    coverage: "Pan-India 100m High-Resolution Gridded Raster",
    temporalResolution: "Annual estimates (2000-2026)",
    formats: ["GeoTIFF", "REST API", "WMS / AWS Open Data"],
    description: "High-resolution spatial demographic datasets created by combining census counts with machine learning and geospatial building/infrastructure covariates. Available at 100m x 100m grid cell resolution.",
    bestFor: "Disaggregated population distribution, emergency evacuation planning, and infrastructure catchment analysis.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_viirs_nightlights",
    category: "03_Population_Socioeconomic",
    categoryName: "Population, Demographics & Socio-Economic",
    name: "NOAA VIIRS Nighttime Lights (Earth Observation Group)",
    provider: "Colorado School of Mines / NOAA / NASA",
    url: "https://eogdata.mines.edu/products/vnl/",
    accessType: "Free Open Access with Registration",
    apiAvailable: true,
    status: "Available",
    coverage: "Global / India Monthly & Annual Composites",
    temporalResolution: "Monthly & Annual (2012-2026)",
    formats: ["Cloud-Optimized GeoTIFF (COG)", "HDF5", "NetCDF"],
    description: "Visible Infrared Imaging Radiometer Suite (VIIRS) Day/Night Band (DNB) nighttime lights data. Captures artificial nocturnal surface luminosity, electrified infrastructure, and industrial activity.",
    bestFor: "Economic activity proxy modeling, rural electrification monitoring, and urban sprawl tracking.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_viirs_gee",
    category: "03_Population_Socioeconomic",
    categoryName: "Population, Demographics & Socio-Economic",
    name: "VIIRS Nighttime Radiance Collection on GEE",
    provider: "NOAA / Google Earth Engine Catalog",
    url: "https://developers.google.com/earth-engine/datasets/catalog/NOAA_VIIRS_DNB_MONTHLY_V1_VCMSLCFG",
    accessType: "Free GEE Cloud Dataset",
    apiAvailable: true,
    status: "Available",
    coverage: "Global Cloud Collection (500m / 15 arc-sec)",
    temporalResolution: "Monthly Stray-Light-Corrected Composites",
    formats: ["GEE Image Collection", "Earth Engine Python / JS API"],
    description: "Monthly stray-light-corrected VIIRS nighttime radiance image collection ready for cloud computation on GEE without downloading large raw files.",
    bestFor: "Time-series zonal statistics of economic growth across Indian districts and smart cities.",
    lastChecked: "2026-08-20"
  },

  // 04 Land Records (3)
  {
    id: "res_dilrmp",
    category: "04_Land_Records",
    categoryName: "Land Records & Cadastral Governance",
    name: "Digital India Land Records Modernization Programme (DILRMP)",
    provider: "Department of Land Resources, Ministry of Rural Development, GoI",
    url: "https://dilrmp.gov.in/",
    accessType: "Official Government MIS Portal",
    apiAvailable: false,
    status: "Available",
    coverage: "National Progress Across All 28 States & 8 UTs",
    temporalResolution: "Monthly MIS Updates",
    formats: ["State Dashboards", "Survey Statistics", "Policy Guidelines"],
    description: "The flagship central sector scheme implementing end-to-end digitization of cadastral maps, computerized Records of Rights (RoRs), integration of registration and revenue offices, and Unique Land Parcel Identification Numbers (ULPIN / Bhu-Aadhaar).",
    bestFor: "Tracking state-wise cadastral digitization status, ULPIN rollout metrics, and land governance policies.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_bhoomi_karnataka",
    category: "04_Land_Records",
    categoryName: "Land Records & Cadastral Governance",
    name: "Bhoomi Karnataka Land Records & RTC Portal",
    provider: "Revenue Department, Government of Karnataka",
    url: "https://landrecords.karnataka.gov.in/",
    accessType: "Public Citizen Portal",
    apiAvailable: true,
    status: "Available",
    coverage: "Karnataka State (All 31 Districts, 240+ Taluks)",
    temporalResolution: "Real-time live mutation database",
    formats: ["Pahani / RTC (Form 16)", "Mutation Status", "Cadastral Tippan", "Bhu-Bharati Maps"],
    description: "India's pioneer online land records management system. Provides online Record of Rights, Tenancy and Crops (RTC/Pahani), mutation application tracking, spatial survey sketches, and dispute registries.",
    bestFor: "Benchmark model for digital cadastral governance, title verification, and rural land ownership records.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_data_gov_in",
    category: "04_Land_Records",
    categoryName: "Land Records & Cadastral Governance",
    name: "Open Government Data (OGD) Platform India",
    provider: "National Informatics Centre (NIC) / MeitY",
    url: "https://www.data.gov.in/",
    accessType: "Open Government Data (OGD License)",
    apiAvailable: true,
    status: "Available",
    coverage: "Pan-India Government Datasets (All Ministries)",
    temporalResolution: "Regularly updated open catalogs",
    formats: ["JSON API", "CSV", "GeoJSON", "XML", "XLSX"],
    description: "The central government open data repository housing over 600,000 resources across agriculture, land revenue, water resources, rural development, urban local bodies, and infrastructure.",
    bestFor: "Locating structured CSV and JSON datasets on state land allocation, crop insurance, and soil health.",
    lastChecked: "2026-08-20"
  },

  // 05 Modeling Tools (6)
  {
    id: "res_smp_pytorch",
    category: "05_Modeling_Tools",
    categoryName: "Geospatial Modeling, AI & Toolkits",
    name: "Segmentation Models PyTorch (SMP)",
    provider: "qubvel-org (Open Source Community)",
    url: "https://github.com/qubvel-org/segmentation_models.pytorch",
    accessType: "Open Source (MIT License)",
    apiAvailable: true,
    status: "Available",
    coverage: "Python Deep Learning Library",
    temporalResolution: "Active Open Source Releases",
    formats: ["PyTorch Modules (Unet, FPN, PSPNet, DeepLabV3+)", "ONNX", "TorchScript"],
    description: "Industry-standard Python deep learning library providing high-performance neural network architectures (U-Net, DeepLabV3+, MANet, Linknet) with hundreds of pretrained vision backbones for satellite image semantic segmentation.",
    bestFor: "Building building footprint extractors, crop parcel classifiers, and road network segmentation models.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_pytorch",
    category: "05_Modeling_Tools",
    categoryName: "Geospatial Modeling, AI & Toolkits",
    name: "PyTorch Deep Learning Framework",
    provider: "PyTorch Foundation / Linux Foundation",
    url: "https://pytorch.org/",
    accessType: "Open Source (BSD License)",
    apiAvailable: true,
    status: "Available",
    coverage: "Machine Learning Platform",
    temporalResolution: "Continuous releases (v2.x)",
    formats: ["Python / C++ API", "CUDA / ROCm / MPS Acceleration"],
    description: "The leading open source machine learning framework that accelerates the path from research prototyping to production deployment. Heavily used in Earth observation AI and geospatial computer vision.",
    bestFor: "Training custom neural networks on multispectral Sentinel-2, Landsat, and drone imagery.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_scikit_learn",
    category: "05_Modeling_Tools",
    categoryName: "Geospatial Modeling, AI & Toolkits",
    name: "Scikit-Learn Machine Learning in Python",
    provider: "Scikit-Learn Community / Inria",
    url: "https://scikit-learn.org/",
    accessType: "Open Source (BSD License)",
    apiAvailable: true,
    status: "Available",
    coverage: "Python Data Science Stack",
    temporalResolution: "Stable Releases",
    formats: ["Python Library", "Joblib model binaries"],
    description: "Simple and efficient tools for predictive data analysis. Provides Random Forests, Gradient Boosting, Support Vector Machines, PCA, and KMeans clustering algorithms widely used in pixel-based land cover classification.",
    bestFor: "Random Forest LULC classification, multi-criteria land suitability weighting, and demographic regression.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_rasterio",
    category: "05_Modeling_Tools",
    categoryName: "Geospatial Modeling, AI & Toolkits",
    name: "Rasterio (Geospatial Raster I/O for Python)",
    provider: "Mapbox / Rasterio Contributors",
    url: "https://rasterio.readthedocs.io/",
    accessType: "Open Source (BSD License)",
    apiAvailable: true,
    status: "Available",
    coverage: "Python GDAL Wrapper",
    temporalResolution: "Active Maintenance",
    formats: ["GeoTIFF", "COG", "VRT", "NetCDF", "NumPy Array"],
    description: "Fast, pythonic raster data access built on top of GDAL. Reads and writes geospatial raster formats and seamlessly converts satellite bands into NumPy arrays for scientific processing.",
    bestFor: "Calculating NDVI/NDWI indices, clipping rasters with polygon masks, and generating Cloud-Optimized GeoTIFFs.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_geopandas",
    category: "05_Modeling_Tools",
    categoryName: "Geospatial Modeling, AI & Toolkits",
    name: "GeoPandas (Vector Geospatial Data in Python)",
    provider: "GeoPandas Community / NumFOCUS",
    url: "https://geopandas.org/",
    accessType: "Open Source (BSD License)",
    apiAvailable: true,
    status: "Available",
    coverage: "Python Vector Stack",
    temporalResolution: "Active Releases",
    formats: ["GeoJSON", "Shapefile", "GeoPackage", "PostGIS", "Parquet / GeoParquet"],
    description: "Extends Pandas data structures to handle spatial operations on geometric types (points, lines, polygons). Enables spatial joins, buffer calculations, CRS reprojections, and choropleth mapping.",
    bestFor: "Cadastral parcel analysis, buffer zone creation for suitability modeling, and vector data manipulation.",
    lastChecked: "2026-08-20"
  },
  {
    id: "res_gee_python_api_modeling",
    category: "05_Modeling_Tools",
    categoryName: "Geospatial Modeling, AI & Toolkits",
    name: "Google Earth Engine Python API (Cloud Modeling)",
    provider: "Google Earth Engine Team",
    url: "https://developers.google.com/earth-engine/guides/python_install",
    accessType: "Cloud Compute SDK",
    apiAvailable: true,
    status: "Available",
    coverage: "Global Cloud Architecture",
    temporalResolution: "Continuous cloud compute",
    formats: ["ee.Image", "ee.FeatureCollection", "TensorFlow Integration"],
    description: "Python interface to the Earth Engine compute engine. Supports export of training patches directly into TensorFlow for training deep convolutional models on Google Cloud Vertex AI.",
    bestFor: "Cloud-native neural network inference, nationwide composites, and serverless geospatial pipelines.",
    lastChecked: "2026-08-20"
  }
];
