/**
 * India Land Information Portal - State & Union Territory Dataset
 * Verified geographic centers, capital coordinates, demographics, and land classification.
 */
const stateDatabase = {
  "andhra pradesh": {
    id: "andhra_pradesh",
    name: "Andhra Pradesh",
    code: "AP",
    zone: "South",
    capital: "Amaravati",
    population: "4.96 Crore",
    populationNum: 49600000,
    area: "162,968 km²",
    areaNum: 162968,
    districts: 26,
    urbanPopulation: "29.5%",
    forestCover: "24.0%",
    literacyRate: "67.4%",
    gdpContribution: "₹14.4 Lakh Cr",
    land: { agriculture: 48, forest: 24, built: 4, water: 5, barren: 19 },
    landUseYear: "2024-25",
    landUseSource: "Directorate of Economics & Statistics / ISRO Bhuvan LULC",
    description: "A major coastal state in southeastern India known for fertile Krishna-Godavari river basins, maritime ports, and expanding industrial corridors.",
    districtList: [
      "Alluri Sitharama Raju", "Anakapalli", "Ananthapuramu", "Annamayya", "Bapatla", 
      "Chittoor", "Dr. B.R. Ambedkar Konaseema", "East Godavari", "Eluru", "Guntur", 
      "Kakinada", "Krishna", "Kurnool", "Nandyal", "NTR", "Palnadu", 
      "Parvathipuram Manyam", "Prakasam", "SPSR Nellore", "Sri Sathya Sai", "Srikakulam", 
      "Tirupati", "Visakhapatnam", "Vizianagaram", "West Godavari", "YSR Kadapa"
    ],
    mapCenter: [16.5062, 80.6480],
    zoom: 7,
    keyProjects: ["Amaravati Capital City GIS Masterplan", "Polavaram Multipurpose Irrigation Project", "Visakhapatnam Port Coastal Economic Zone"]
  },
  "arunachal pradesh": {
    id: "arunachal_pradesh",
    name: "Arunachal Pradesh",
    code: "AR",
    zone: "North East",
    capital: "Itanagar",
    population: "13.84 Lakh",
    populationNum: 1384000,
    area: "83,743 km²",
    areaNum: 83743,
    districts: 28,
    urbanPopulation: "22.9%",
    forestCover: "78.0%",
    literacyRate: "65.4%",
    gdpContribution: "₹37,000 Cr",
    land: { agriculture: 4, forest: 78, built: 1, water: 3, barren: 14 },
    landUseYear: "2024-25",
    landUseSource: "Forest Survey of India (FSI) 2023 & Bhuvan",
    description: "The northeasternmost Himalayan state of India, characterized by rugged alpine mountains, dense primary rainforests, and rich biodiversity.",
    districtList: [
      "Anjaw", "Changlang", "Dibang Valley", "East Kameng", "East Siang", "Itanagar", 
      "Kamle", "Kra Daadi", "Kurung Kumey", "Lepa Rada", "Lohit", "Longding", 
      "Lower Dibang Valley", "Lower Siang", "Lower Subansiri", "Namsai", "Pakke-Kessang", 
      "Papum Pare", "Shi Yomi", "Siang", "Tawang", "Tirap", "Upper Siang", "Upper Subansiri", 
      "West Kameng", "West Siang", "Bichom", "Keyi Panyor"
    ],
    mapCenter: [27.0844, 93.6053],
    zoom: 7,
    keyProjects: ["Frontier Highway Geospatial Alignment", "Dibang Multipurpose Hydropower GIS Zone", "Tawang Eco-Tourism Master Plan"]
  },
  "assam": {
    id: "assam",
    name: "Assam",
    code: "AS",
    zone: "North East",
    capital: "Dispur",
    population: "3.12 Crore",
    populationNum: 31200000,
    area: "78,438 km²",
    areaNum: 78438,
    districts: 35,
    urbanPopulation: "15.3%",
    forestCover: "36.0%",
    literacyRate: "72.2%",
    gdpContribution: "₹5.6 Lakh Cr",
    land: { agriculture: 54, forest: 36, built: 4, water: 4, barren: 2 },
    landUseYear: "2024-25",
    landUseSource: "Assam Remote Sensing Application Centre (ARSAC)",
    description: "The gateway to Northeast India, centered along the Brahmaputra River valley, famous for tea estates, wildlife reserves (Kaziranga), and petroleum resources.",
    districtList: [
      "Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", "Chirang", 
      "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Dima Hasao", "Goalpara", "Golaghat", 
      "Hailakandi", "Hojai", "Jorhat", "Kamrup", "Kamrup Metropolitan", "Karbi Anglong", 
      "Karimganj", "Kokrajhar", "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", 
      "Sivasagar", "Sonitpur", "South Salmara-Mankachar", "Tinsukia", "Udalguri", 
      "West Karbi Anglong", "Bajali", "Tamulpur"
    ],
    mapCenter: [26.1445, 91.7362],
    zoom: 7,
    keyProjects: ["Mission Basundhara Land Record Digitization", "Brahmaputra Flood Risk GIS Mapping", "Guwahati Smart City Geospatial Plan"]
  },
  "bihar": {
    id: "bihar",
    name: "Bihar",
    code: "BR",
    zone: "East",
    capital: "Patna",
    population: "10.41 Crore",
    populationNum: 104100000,
    area: "94,163 km²",
    areaNum: 94163,
    districts: 38,
    urbanPopulation: "11.3%",
    forestCover: "7.8%",
    literacyRate: "61.8%",
    gdpContribution: "₹8.5 Lakh Cr",
    land: { agriculture: 60, forest: 8, built: 14, water: 4, barren: 14 },
    landUseYear: "2024-25",
    landUseSource: "Bihar Land Revenue & Survey Directorate / Bhuvan",
    description: "A heavily populated, intensively farmed state in the heart of the Indo-Gangetic Plains, traversed by the Ganges River.",
    districtList: [
      "Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur", 
      "Buxar", "Darbhanga", "East Champaran", "Gaya", "Gopalganj", "Jamui", "Jehanabad", 
      "Kaimur", "Katihar", "Khagaria", "Kishanganj", "Lakhisarai", "Madhepura", "Madhubani", 
      "Munger", "Muzaffarpur", "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", 
      "Saharsa", "Samastipur", "Saran", "Sheikhpura", "Sheohar", "Sitamarhi", "Siwan", 
      "Supaul", "Vaishali", "West Champaran"
    ],
    mapCenter: [25.5941, 85.1376],
    zoom: 7,
    keyProjects: ["Bihar Special Land Survey (Vishesh Sarve)", "Patna Metropolitan GIS Cadastre", "Kosi-Mechi River Link Spatial Model"]
  },
  "chhattisgarh": {
    id: "chhattisgarh",
    name: "Chhattisgarh",
    code: "CG",
    zone: "Central",
    capital: "Raipur",
    population: "2.55 Crore",
    populationNum: 25500000,
    area: "135,192 km²",
    areaNum: 135192,
    districts: 33,
    urbanPopulation: "23.2%",
    forestCover: "44.0%",
    literacyRate: "70.3%",
    gdpContribution: "₹5.0 Lakh Cr",
    land: { agriculture: 42, forest: 44, built: 3, water: 4, barren: 7 },
    landUseYear: "2024-25",
    landUseSource: "Chhattisgarh State Centre for Geo-Informatics (CSCG)",
    description: "A heavily forested, mineral-rich central Indian state known as the 'Rice Bowl of Central India', holding massive coal and iron-ore reserves.",
    districtList: [
      "Balod", "Baloda Bazar", "Balrampur", "Bastar", "Bemetara", "Bijapur", "Bilaspur", 
      "Dantewada", "Dhamtari", "Durg", "Gariaband", "Gaurela-Pendra-Marwahi", "Janjgir-Champa", 
      "Jashpur", "Kabirdham", "Kanker", "Kondagaon", "Korba", "Koriya", "Mahasamund", 
      "Manendragarh-Chirmiri-Bharatpur", "Mohla-Manpur-Ambagarh Chowki", "Mungeli", "Narayanpur", 
      "Raigarh", "Raipur", "Rajnandgaon", "Sarangarh-Bilaigarh", "Sakti", "Sukma", 
      "Surajpur", "Surguja", "Khairagarh-Chhuikhadan-Gandai"
    ],
    mapCenter: [21.2514, 81.6296],
    zoom: 7,
    keyProjects: ["Bhuiyan Digital Land Records Cadastre", "Hasdeo Forest Spatial Audit", "Nava Raipur Smart Capital GIS"]
  },
  "goa": {
    id: "goa",
    name: "Goa",
    code: "GA",
    zone: "West",
    capital: "Panaji",
    population: "14.59 Lakh",
    populationNum: 1459000,
    area: "3,702 km²",
    areaNum: 3702,
    districts: 2,
    urbanPopulation: "62.2%",
    forestCover: "60.0%",
    literacyRate: "88.7%",
    gdpContribution: "₹1.0 Lakh Cr",
    land: { agriculture: 28, forest: 60, built: 6, water: 3, barren: 3 },
    landUseYear: "2024-25",
    landUseSource: "Goa Directorate of Settlement and Land Records (DSLR)",
    description: "India's coastal paradise on the Konkan coast, world-renowned for tourism, Western Ghats ecology, and sophisticated coastal zone management.",
    districtList: ["North Goa", "South Goa"],
    mapCenter: [15.4909, 73.8278],
    zoom: 9,
    keyProjects: ["Coastal Zone Management Plan (CZMP 2026)", "Goa Cadastral Property Card Portal", "Mopa Aerocity GIS Buffer"]
  },
  "gujarat": {
    id: "gujarat",
    name: "Gujarat",
    code: "GJ",
    zone: "West",
    capital: "Gandhinagar",
    population: "6.04 Crore",
    populationNum: 60400000,
    area: "196,024 km²",
    areaNum: 196024,
    districts: 33,
    urbanPopulation: "42.6%",
    forestCover: "11.0%",
    literacyRate: "78.0%",
    gdpContribution: "₹25.6 Lakh Cr",
    land: { agriculture: 53, forest: 11, built: 6, water: 3, barren: 27 },
    landUseYear: "2024-25",
    landUseSource: "BISAG-N (Bhaskaracharya National Institute for Geo-informatics)",
    description: "A leading industrial and economic powerhouse on India's western coast with 1,600 km coastline, major ports, renewable energy parks (Khavda), and advanced GIS governance.",
    districtList: [
      "Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch", "Bhavnagar", 
      "Botad", "Chhota Udaipur", "Dahod", "Dang", "Devbhumi Dwarka", "Gandhinagar", 
      "Gir Somnath", "Jamnagar", "Junagadh", "Kheda", "Kutch", "Mahisagar", "Mehsana", 
      "Morbi", "Narmada", "Navsari", "Panchmahal", "Patan", "Porbandar", "Rajkot", 
      "Sabarkantha", "Surat", "Surendranagar", "Tapi", "Vadodara", "Valsad"
    ],
    mapCenter: [23.2156, 72.6369],
    zoom: 7,
    keyProjects: ["Dholera SIR Mega Smart City GIS", "Khavda 30GW Hybrid Renewable Park", "AnyROR Digital Gujarat Land Records"]
  },
  "haryana": {
    id: "haryana",
    name: "Haryana",
    code: "HR",
    zone: "North",
    capital: "Chandigarh",
    population: "2.54 Crore",
    populationNum: 25400000,
    area: "44,212 km²",
    areaNum: 44212,
    districts: 22,
    urbanPopulation: "34.9%",
    forestCover: "3.6%",
    literacyRate: "75.6%",
    gdpContribution: "₹11.2 Lakh Cr",
    land: { agriculture: 78, forest: 4, built: 12, water: 2, barren: 4 },
    landUseYear: "2024-25",
    landUseSource: "Haryana Space Applications Centre (HARSAC)",
    description: "An agricultural and industrial powerhouse surrounding the National Capital Region (NCR), with major tech hubs in Gurugram.",
    districtList: [
      "Ambala", "Bhiwani", "Charkhi Dadri", "Faridabad", "Fatehabad", "Gurugram", 
      "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh", 
      "Nuh", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"
    ],
    mapCenter: [29.0588, 76.0856],
    zoom: 8,
    keyProjects: ["Lal Dora Free Drone Mapping (SVAMITVA)", "KMP Expressway Logistics Belt", "HARSAC Land Use Monitoring"]
  },
  "himachal pradesh": {
    id: "himachal_pradesh",
    name: "Himachal Pradesh",
    code: "HP",
    zone: "North",
    capital: "Shimla",
    population: "68.65 Lakh",
    populationNum: 6865000,
    area: "55,673 km²",
    areaNum: 55673,
    districts: 12,
    urbanPopulation: "10.0%",
    forestCover: "66.5%",
    literacyRate: "82.8%",
    gdpContribution: "₹2.1 Lakh Cr",
    land: { agriculture: 10, forest: 66, built: 2, water: 2, barren: 20 },
    landUseYear: "2024-25",
    landUseSource: "Himachal Pradesh Council for Science & Tech (HIMCOSTE)",
    description: "A northern mountainous Himalayan state known for hydroelectric power, apple orchards, tourism, and rigorous slope risk zoning.",
    districtList: [
      "Bilaspur", "Chamba", "Hamirpur", "Kangra", "Kinnaur", "Kullu", "Lahaul and Spiti", 
      "Mandi", "Shimla", "Sirmaur", "Solan", "Una"
    ],
    mapCenter: [31.1048, 77.1734],
    zoom: 7,
    keyProjects: ["HIMCOSTE Landslide Early Warning GIS", "Shimla Master Plan Urban Siting", "Hydroelectric Catchment Basin GIS"]
  },
  "jharkhand": {
    id: "jharkhand",
    name: "Jharkhand",
    code: "JH",
    zone: "East",
    capital: "Ranchi",
    population: "3.30 Crore",
    populationNum: 33000000,
    area: "79,714 km²",
    areaNum: 79714,
    districts: 24,
    urbanPopulation: "24.0%",
    forestCover: "29.8%",
    literacyRate: "66.4%",
    gdpContribution: "₹4.7 Lakh Cr",
    land: { agriculture: 38, forest: 30, built: 6, water: 3, barren: 23 },
    landUseYear: "2024-25",
    landUseSource: "Jharkhand Space Applications Center (JSAC)",
    description: "Mineral-rich eastern state holding over 40% of India's mineral reserves including coal, iron ore, and copper.",
    districtList: [
      "Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum", "Garhwa", 
      "Giridih", "Godda", "Gumla", "Hazaribagh", "Jamtara", "Khunti", "Koderma", 
      "Latehar", "Lohardaga", "Pakur", "Palamu", "Ramgarh", "Ranchi", "Sahebganj", 
      "Seraikela Kharsawan", "Simdega", "West Singhbhum"
    ],
    mapCenter: [23.3441, 85.3096],
    zoom: 7,
    keyProjects: ["Jharbhoomi Land Record Digitization", "Mining Lease Spatial Geofencing", "Ranchi Smart Urban Masterplan"]
  },
  "karnataka": {
    id: "karnataka",
    name: "Karnataka",
    code: "KA",
    zone: "South",
    capital: "Bengaluru",
    population: "6.11 Crore",
    populationNum: 61100000,
    area: "191,791 km²",
    areaNum: 191791,
    districts: 31,
    urbanPopulation: "38.7%",
    forestCover: "20.1%",
    literacyRate: "75.4%",
    gdpContribution: "₹25.0 Lakh Cr",
    land: { agriculture: 55, forest: 20, built: 7, water: 3, barren: 15 },
    landUseYear: "2024-25",
    landUseSource: "Karnataka State Remote Sensing Applications Centre (KSRSAC) / Bhoomi",
    description: "India's premier technology and innovation hub, home to Bengaluru, pioneer in digital land records (Bhoomi), and Western Ghats forests.",
    districtList: [
      "Bagalkot", "Ballari", "Belagavi", "Bengaluru Rural", "Bengaluru Urban", "Bidar", 
      "Chamarajanagar", "Chikkaballapur", "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", 
      "Davanagere", "Dharwad", "Gadag", "Hassan", "Haveri", "Kalaburagi", "Kodagu", 
      "Kolar", "Koppal", "Mandya", "Mysuru", "Raichur", "Ramanagara", "Shivamogga", 
      "Tumakuru", "Udupi", "Uttara Kannada", "Vijayanagara", "Vijayapura", "Yadgir"
    ],
    mapCenter: [12.9716, 77.5946],
    zoom: 7,
    keyProjects: ["Bhoomi 3.0 Real-time Mutation Cadastre", "Karnataka GIS (K-GIS) Enterprise Portal", "BMRDA Metropolitan Spatial Plan"]
  },
  "kerala": {
    id: "kerala",
    name: "Kerala",
    code: "KL",
    zone: "South",
    capital: "Thiruvananthapuram",
    population: "3.34 Crore",
    populationNum: 33400000,
    area: "38,863 km²",
    areaNum: 38863,
    districts: 14,
    urbanPopulation: "47.7%",
    forestCover: "54.7%",
    literacyRate: "94.0%",
    gdpContribution: "₹11.3 Lakh Cr",
    land: { agriculture: 52, forest: 29, built: 12, water: 4, barren: 3 },
    landUseYear: "2024-25",
    landUseSource: "Kerala State Remote Sensing and Environment Centre (KSREC)",
    description: "A tropical coastal state boasting India's highest Human Development Index, extensive backwaters, and plantation hills.",
    districtList: [
      "Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", 
      "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", 
      "Thrissur", "Wayanad"
    ],
    mapCenter: [8.5241, 76.9366],
    zoom: 8,
    keyProjects: ["Ente Bhoomi Digital Resurvey Initiative", "Kerala Spatial Data Infrastructure (KSDI)", "Wayanad Landslide Hazard Zone Mapping"]
  },
  "madhya pradesh": {
    id: "madhya_pradesh",
    name: "Madhya Pradesh",
    code: "MP",
    zone: "Central",
    capital: "Bhopal",
    population: "7.26 Crore",
    populationNum: 72600000,
    area: "308,245 km²",
    areaNum: 308245,
    districts: 55,
    urbanPopulation: "27.6%",
    forestCover: "25.1%",
    literacyRate: "69.3%",
    gdpContribution: "₹13.6 Lakh Cr",
    land: { agriculture: 49, forest: 28, built: 4, water: 3, barren: 16 },
    landUseYear: "2024-25",
    landUseSource: "Madhya Pradesh Council of Science & Technology (MPCST) / MP Bhulekh",
    description: "The geographical heart of India, possessing the nation's largest total forest cover area, prominent tiger reserves, and fertile agricultural basins.",
    districtList: [
      "Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul", 
      "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", 
      "Dewas", "Dhar", "Dindori", "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore", 
      "Jabalpur", "Jhabua", "Katni", "Khandwa", "Khargone", "Mandla", "Mandsaur", 
      "Morena", "Narsinghpur", "Neemuch", "Niwari", "Panna", "Raisen", "Rajgarh", 
      "Ratlam", "Rewa", "Sagar", "Satna", "Sehore", "Seoni", "Shahdol", "Shajapur", 
      "Sheopur", "Shivpuri", "Sidhi", "Singrauli", "Tikamgarh", "Ujjain", "Umaria", 
      "Vidisha", "Mauganj", "Maihar", "Pandhurna"
    ],
    mapCenter: [23.2599, 77.4126],
    zoom: 6,
    keyProjects: ["MP Bhulekh Integrated Land Registry", "Ken-Betwa River Linkage Spatial Model", "Panna Tiger Reserve Corridor GIS"]
  },
  "maharashtra": {
    id: "maharashtra",
    name: "Maharashtra",
    code: "MH",
    zone: "West",
    capital: "Mumbai",
    population: "11.24 Crore",
    populationNum: 112400000,
    area: "307,713 km²",
    areaNum: 307713,
    districts: 36,
    urbanPopulation: "45.2%",
    forestCover: "16.5%",
    literacyRate: "82.3%",
    gdpContribution: "₹42.7 Lakh Cr",
    land: { agriculture: 57, forest: 17, built: 6, water: 3, barren: 17 },
    landUseYear: "2024-25",
    landUseSource: "Maharashtra Remote Sensing Application Centre (MRSAC) / Mahabhulekh",
    description: "India's financial and industrial capital state, home to Mumbai, massive manufacturing corridors, and extensive agricultural plateaus.",
    districtList: [
      "Ahmednagar", "Akola", "Amravati", "Aurangabad (Chhatrapati Sambhajinagar)", "Beed", 
      "Bhandara", "Buldhana", "Chandrapur", "Dhule", "Gadchiroli", "Gondia", "Hingoli", 
      "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", 
      "Nanded", "Nandurbar", "Nashik", "Osmanabad (Dharashiv)", "Palghar", "Parbhani", 
      "Pune", "Raigad", "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", 
      "Thane", "Wardha", "Washim", "Yavatmal"
    ],
    mapCenter: [19.0760, 72.8777],
    zoom: 7,
    keyProjects: ["Samruddhi Mahamarg Expressway GIS Corridor", "Mahabhulekh 7/12 & e-Ferfar Mutation Cadastre", "MMRDA Regional Master Plan 2036"]
  },
  "manipur": {
    id: "manipur",
    name: "Manipur",
    code: "MN",
    zone: "North East",
    capital: "Imphal",
    population: "28.56 Lakh",
    populationNum: 2856000,
    area: "22,327 km²",
    areaNum: 22327,
    districts: 16,
    urbanPopulation: "29.2%",
    forestCover: "74.3%",
    literacyRate: "76.9%",
    gdpContribution: "₹45,000 Cr",
    land: { agriculture: 10, forest: 76, built: 2, water: 3, barren: 9 },
    landUseYear: "2024-25",
    landUseSource: "Manipur State Remote Sensing Applications Centre (MARSAC)",
    description: "A scenic northeastern state characterized by the Imphal Valley, Loktak Lake (floating phumdis), and lush hills.",
    districtList: [
      "Bishnupur", "Chandel", "Churachandpur", "Imphal East", "Imphal West", "Jiribam", 
      "Kakching", "Kamjong", "Kangpokpi", "Noney", "Pherzawl", "Senapati", "Tamenglong", 
      "Tengnoupal", "Thoubal", "Ukhrul"
    ],
    mapCenter: [24.8170, 93.9368],
    zoom: 8,
    keyProjects: ["Loktak Lake Wetland Spatial Restoration", "Loucha Pathap Digital Land Records", "Trans-Asian Highway Geospatial Corridor"]
  },
  "meghalaya": {
    id: "meghalaya",
    name: "Meghalaya",
    code: "ML",
    zone: "North East",
    capital: "Shillong",
    population: "29.67 Lakh",
    populationNum: 2967000,
    area: "22,429 km²",
    areaNum: 22429,
    districts: 12,
    urbanPopulation: "20.1%",
    forestCover: "76.0%",
    literacyRate: "74.4%",
    gdpContribution: "₹46,000 Cr",
    land: { agriculture: 12, forest: 76, built: 2, water: 1, barren: 9 },
    landUseYear: "2024-25",
    landUseSource: "North Eastern Space Applications Centre (NESAC), Umiam",
    description: "'Abode of Clouds', home to living root bridges, the wettest areas on Earth (Mawsynram/Cherrapunji), and customary community forests.",
    districtList: [
      "East Garo Hills", "East Jaintia Hills", "East Khasi Hills", "Eastern West Khasi Hills", 
      "North Garo Hills", "Ri-Bhoi", "South Garo Hills", "South West Garo Hills", 
      "South West Khasi Hills", "West Garo Hills", "West Jaintia Hills", "West Khasi Hills"
    ],
    mapCenter: [25.5788, 91.8933],
    zoom: 8,
    keyProjects: ["NESAC Geospatial Hub & Early Flood Warning", "Meghalaya Community Forest GIS Inventory", "Shillong Eco-Tourism Master Plan"]
  },
  "mizoram": {
    id: "mizoram",
    name: "Mizoram",
    code: "MZ",
    zone: "North East",
    capital: "Aizawl",
    population: "10.97 Lakh",
    populationNum: 1097000,
    area: "21,081 km²",
    areaNum: 21081,
    districts: 11,
    urbanPopulation: "52.1%",
    forestCover: "84.5%",
    literacyRate: "91.3%",
    gdpContribution: "₹35,000 Cr",
    land: { agriculture: 6, forest: 85, built: 1, water: 1, barren: 7 },
    landUseYear: "2024-25",
    landUseSource: "Mizoram Remote Sensing Application Centre (MIRSAC)",
    description: "A steep mountain state with the highest forest cover percentage in India and progressive community forestry management.",
    districtList: [
      "Aizawl", "Champhai", "Hnahthial", "Khawzawl", "Kolasib", "Lawngtlai", "Lunglei", 
      "Mamit", "Saitual", "Serchhip", "Siaha"
    ],
    mapCenter: [23.7271, 92.7176],
    zoom: 8,
    keyProjects: ["Kaladan Multi-Modal Transit GIS Corridor", "MIRSAC Bamboo Forest Spatial Inventory", "Aizawl Slope Risk Mitigation Map"]
  },
  "nagaland": {
    id: "nagaland",
    name: "Nagaland",
    code: "NL",
    zone: "North East",
    capital: "Kohima",
    population: "19.79 Lakh",
    populationNum: 1979000,
    area: "16,579 km²",
    areaNum: 16579,
    districts: 16,
    urbanPopulation: "28.9%",
    forestCover: "73.9%",
    literacyRate: "79.6%",
    gdpContribution: "₹39,000 Cr",
    land: { agriculture: 18, forest: 74, built: 2, water: 1, barren: 5 },
    landUseYear: "2024-25",
    landUseSource: "Nagaland GIS & Remote Sensing Centre (NGRSC)",
    description: "A vibrant tribal state in Northeast India with rich indigenous cultural traditions and community-owned mountain forests.",
    districtList: [
      "Chümoukedima", "Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", 
      "Niuland", "Noklak", "Peren", "Phek", "Shamator", "Tseminyü", "Tuensang", "Wokha", "Zünheboto"
    ],
    mapCenter: [25.6751, 94.1086],
    zoom: 8,
    keyProjects: ["Nagaland Spatial Data Infrastructure (NSDI)", "Community Jhum Land Satellite Monitoring", "Kohima Smart City 3D GIS"]
  },
  "odisha": {
    id: "odisha",
    name: "Odisha",
    code: "OD",
    zone: "East",
    capital: "Bhubaneswar",
    population: "4.20 Crore",
    populationNum: 42000000,
    area: "155,707 km²",
    areaNum: 155707,
    districts: 30,
    urbanPopulation: "16.7%",
    forestCover: "33.5%",
    literacyRate: "72.9%",
    gdpContribution: "₹8.6 Lakh Cr",
    land: { agriculture: 45, forest: 33, built: 5, water: 4, barren: 13 },
    landUseYear: "2024-25",
    landUseSource: "Odisha Space Applications Centre (ORSAC) / Bhulekh Odisha",
    description: "An eastern coastal state endowed with enormous mineral wealth, Asia's largest brackish lagoon (Chilika Lake), and pioneering disaster GIS.",
    districtList: [
      "Angul", "Balangir", "Balasore", "Bargarh", "Bhadrak", "Boudh", "Cuttack", 
      "Deogarh", "Dhenkanal", "Gajapati", "Ganjam", "Jagatsinghpur", "Jajpur", "Jharsuguda", 
      "Kalahandi", "Kandhamal", "Kendrapara", "Kendujhar", "Khordha", "Koraput", "Malkangiri", 
      "Mayurbhanj", "Nabarangpur", "Nayagarh", "Nuapada", "Puri", "Rayagada", "Sambalpur", 
      "Subarnapur", "Sundargarh"
    ],
    mapCenter: [20.2961, 85.8245],
    zoom: 7,
    keyProjects: ["Bhulekh Odisha & e-Pauti Digital Cadastre", "ORSAC Coastal Cyclone Inundation Model", "Bhubaneswar One Integrated Urban GIS"]
  },
  "punjab": {
    id: "punjab",
    name: "Punjab",
    code: "PB",
    zone: "North",
    capital: "Chandigarh",
    population: "2.77 Crore",
    populationNum: 27700000,
    area: "50,362 km²",
    areaNum: 50362,
    districts: 23,
    urbanPopulation: "37.5%",
    forestCover: "3.7%",
    literacyRate: "75.8%",
    gdpContribution: "₹7.4 Lakh Cr",
    land: { agriculture: 83, forest: 4, built: 9, water: 1, barren: 3 },
    landUseYear: "2024-25",
    landUseSource: "Punjab Remote Sensing Centre (PRSC), Ludhiana",
    description: "The 'Granary of India', fed by the Indus river system, exhibiting the nation's highest cropping intensity and canal irrigation networks.",
    districtList: [
      "Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur", 
      "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Ludhiana", "Malerkotla", "Mansa", 
      "Moga", "Muktsar", "Pathankot", "Patiala", "Rupnagar", "Sahibzada Ajit Singh Nagar (Mohali)", 
      "Sangrur", "Shahid Bhagat Singh Nagar (Nawanshahr)", "Tarn Taran"
    ],
    mapCenter: [30.7333, 76.7794],
    zoom: 8,
    keyProjects: ["PRSC Crop Stubble Thermal Hotspot Monitoring", "Punjab Land Records Society (PLRS) Fard", "Groundwater Table Depletion Spatial Map"]
  },
  "rajasthan": {
    id: "rajasthan",
    name: "Rajasthan",
    code: "RJ",
    zone: "North",
    capital: "Jaipur",
    population: "6.85 Crore",
    populationNum: 68500000,
    area: "342,239 km²",
    areaNum: 342239,
    districts: 50,
    urbanPopulation: "24.9%",
    forestCover: "4.9%",
    literacyRate: "66.1%",
    gdpContribution: "₹15.7 Lakh Cr",
    land: { agriculture: 51, forest: 8, built: 4, water: 1, barren: 36 },
    landUseYear: "2024-25",
    landUseSource: "State Remote Sensing Application Centre (SRSAC), Jodhpur / Apna Khata",
    description: "India's largest state by area, spanning the Thar Desert, Aravalli mountain range, palace heritage, and world-class solar parks (Bhadla).",
    districtList: [
      "Ajmer", "Alwar", "Anupgarh", "Balotra", "Banswara", "Baran", "Barmer", "Beawar", 
      "Bharatpur", "Bhilwara", "Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa", 
      "Deeg", "Dholpur", "Didwana-Kuchaman", "Dudu", "Dungarpur", "Ganganagar", "Gangapur City", 
      "Hanumangarh", "Jaipur", "Jaipur Rural", "Jaisalmer", "Jalore", "Jhalawar", "Jhunjhunu", 
      "Jodhpur", "Jodhpur Rural", "Karauli", "Kekri", "Khairthal-Tijara", "Kota", "Kotputli-Behror", 
      "Nagaur", "Neem Ka Thana", "Pali", "Phalodi", "Pratapgarh", "Rajsamand", "Salumbar", 
      "Sanchore", "Sawai Madhopur", "Shahpura", "Sikar", "Sirohi", "Tonk", "Udaipur"
    ],
    mapCenter: [26.9124, 75.7873],
    zoom: 6,
    keyProjects: ["Bhadla & Thar Solar Park GIS Mapping", "Apna Khata (E-Dharti) Land Cadastre", "Indira Gandhi Canal Command Area GIS"]
  },
  "sikkim": {
    id: "sikkim",
    name: "Sikkim",
    code: "SK",
    zone: "North East",
    capital: "Gangtok",
    population: "6.11 Lakh",
    populationNum: 611000,
    area: "7,096 km²",
    areaNum: 7096,
    districts: 6,
    urbanPopulation: "25.2%",
    forestCover: "47.1%",
    literacyRate: "81.4%",
    gdpContribution: "₹45,000 Cr",
    land: { agriculture: 11, forest: 47, built: 2, water: 2, barren: 38 },
    landUseYear: "2024-25",
    landUseSource: "Sikkim State Remote Sensing Applications Centre (SSRSAC)",
    description: "India's first 100% certified organic state, crowned by Kangchenjunga, alpine glaciers, and sacred mountain lakes.",
    districtList: ["Gangtok", "Gyalshing", "Pakyong", "Namchi", "Mangan", "Soreng"],
    mapCenter: [27.3389, 88.6065],
    zoom: 9,
    keyProjects: ["Glacial Lake Outburst Flood (GLOF) Early Warning", "Organic Farming GIS Cadastral Traceability", "Gangtok Urban Slope Master Plan"]
  },
  "tamil nadu": {
    id: "tamil_nadu",
    name: "Tamil Nadu",
    code: "TN",
    zone: "South",
    capital: "Chennai",
    population: "7.21 Crore",
    populationNum: 72100000,
    area: "130,058 km²",
    areaNum: 130058,
    districts: 38,
    urbanPopulation: "48.4%",
    forestCover: "20.3%",
    literacyRate: "80.1%",
    gdpContribution: "₹31.5 Lakh Cr",
    land: { agriculture: 45, forest: 21, built: 12, water: 4, barren: 18 },
    landUseYear: "2024-25",
    landUseSource: "Institute of Remote Sensing (IRS), Anna University / Patta Chitta",
    description: "One of India's most industrialized southern states, leading in automobile manufacturing, electronics, textiles, wind energy, and digital Patta Chitta land records.",
    districtList: [
      "Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", 
      "Dindigul", "Erode", "Kallakurichi", "Kanchipuram", "Kanyakumari", "Karur", 
      "Krishnagiri", "Madurai", "Mayiladuthurai", "Nagapattinam", "Namakkal", "Nilgiris", 
      "Perambalur", "Pudukkottai", "Ramanathapuram", "Ranipet", "Salem", "Sivaganga", 
      "Tenkasi", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", 
      "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Vellore", 
      "Viluppuram", "Virudhunagar"
    ],
    mapCenter: [13.0827, 80.2707],
    zoom: 7,
    keyProjects: ["Tamil Nilam Digital Land Registry & Patta Chitta", "CMDA Chennai Regional GIS 2046", "Tamil Nadu Spatial Data Infrastructure (TNSDI)"]
  },
  "telangana": {
    id: "telangana",
    name: "Telangana",
    code: "TS",
    zone: "South",
    capital: "Hyderabad",
    population: "3.50 Crore",
    populationNum: 35000000,
    area: "112,077 km²",
    areaNum: 112077,
    districts: 33,
    urbanPopulation: "38.9%",
    forestCover: "18.2%",
    literacyRate: "72.8%",
    gdpContribution: "₹14.0 Lakh Cr",
    land: { agriculture: 54, forest: 24, built: 6, water: 4, barren: 12 },
    landUseYear: "2024-25",
    landUseSource: "Telangana State Remote Sensing Applications Centre (TRAC) / Dharani",
    description: "A major IT, biotechnology, and aerospace powerhouse centered in Hyderabad, with the world's largest lift irrigation system (Kaleshwaram).",
    districtList: [
      "Adilabad", "Bhadradri Kothagudem", "Hanamkonda", "Hyderabad", "Jagtial", "Jangaon", 
      "Jayashankar Bhupalpally", "Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khammam", 
      "Kumuram Bheem Asifabad", "Mahabubabad", "Mahabubnagar", "Mancherial", "Medak", 
      "Medchal-Malkajgiri", "Mulugu", "Nagarkurnool", "Nalgonda", "Narayanpet", "Nirmal", 
      "Nizamabad", "Peddapalli", "Rajanna Sircilla", "Rangareddy", "Sangareddy", "Siddipet", 
      "Suryapet", "Vikarabad", "Wanaparthy", "Warangal", "Yadadri Bhuvanagiri"
    ],
    mapCenter: [17.3850, 78.4867],
    zoom: 7,
    keyProjects: ["Dharani Integrated Land Record Management System", "Kaleshwaram Lift Irrigation GIS Command", "Hyderabad Outer Ring Road Master Growth Zone"]
  },
  "tripura": {
    id: "tripura",
    name: "Tripura",
    code: "TR",
    zone: "North East",
    capital: "Agartala",
    population: "36.74 Lakh",
    populationNum: 3674000,
    area: "10,491 km²",
    areaNum: 10491,
    districts: 8,
    urbanPopulation: "26.2%",
    forestCover: "73.6%",
    literacyRate: "87.2%",
    gdpContribution: "₹72,000 Cr",
    land: { agriculture: 27, forest: 60, built: 5, water: 3, barren: 5 },
    landUseYear: "2024-25",
    landUseSource: "Tripura Space Applications Centre (TSAC)",
    description: "Bordered on three sides by Bangladesh, rich in natural gas, bamboo crafts, rubber plantations, and lush hills.",
    districtList: [
      "Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura", 
      "Unakoti", "West Tripura"
    ],
    mapCenter: [23.8315, 91.2868],
    zoom: 8,
    keyProjects: ["Jarnabhoomi Digital Land Cadastre", "Indo-Bangladesh Agartala Rail Corridor GIS", "Rubber Plantation Spatial Monitoring"]
  },
  "uttar pradesh": {
    id: "uttar_pradesh",
    name: "Uttar Pradesh",
    code: "UP",
    zone: "North",
    capital: "Lucknow",
    population: "19.98 Crore",
    populationNum: 199800000,
    area: "240,928 km²",
    areaNum: 240928,
    districts: 75,
    urbanPopulation: "22.3%",
    forestCover: "6.1%",
    literacyRate: "67.7%",
    gdpContribution: "₹25.0 Lakh Cr",
    land: { agriculture: 68, forest: 6, built: 13, water: 3, barren: 10 },
    landUseYear: "2024-25",
    landUseSource: "Remote Sensing Applications Centre, UP (RSAC-UP) / Bhulekh UP",
    description: "India's most populous state across the fertile Gangetic plain, with extensive expressways (Ganga, Purvanchal) and massive agro-industrial output.",
    districtList: [
      "Agra", "Aligarh", "Ambedkar Nagar", "Amethi", "Amroha", "Auraiya", "Ayodhya", 
      "Azamgarh", "Baghpat", "Bahraich", "Ballia", "Balrampur", "Banda", "Barabanki", 
      "Bareilly", "Basti", "Bhadohi", "Bijnor", "Budaun", "Bulandshahr", "Chandauli", 
      "Chitrakoot", "Deoria", "Etah", "Etawah", "Farrukhabad", "Fatehpur", "Firozabad", 
      "Gautam Buddha Nagar (Noida)", "Ghaziabad", "Ghazipur", "Gonda", "Gorakhpur", 
      "Hamirpur", "Hapur", "Hardoi", "Hathras", "Jalaun", "Jaunpur", "Jhansi", "Kannauj", 
      "Kanpur Dehat", "Kanpur Nagar", "Kasganj", "Kaushambi", "Kheri", "Kushinagar", 
      "Lalitpur", "Lucknow", "Maharajganj", "Mahoba", "Mainpuri", "Mathura", "Mau", 
      "Meerut", "Mirzapur", "Moradabad", "Muzaffarnagar", "Pilibhit", "Pratapgarh", 
      "Prayagraj", "Raebareli", "Rampur", "Saharanpur", "Sambhal", "Sant Kabir Nagar", 
      "Shahjahanpur", "Shamli", "Shravasti", "Siddharthnagar", "Sitapur", "Sonbhadra", 
      "Sultanpur", "Unnao", "Varanasi"
    ],
    mapCenter: [26.8467, 80.9462],
    zoom: 6,
    keyProjects: ["Bhulekh UP Real-time Khasra Cadastre", "Ganga Expressway Geospatial Corridor", "Noida International Airport (Jewar) Aerocity"]
  },
  "uttarakhand": {
    id: "uttarakhand",
    name: "Uttarakhand",
    code: "UK",
    zone: "North",
    capital: "Dehradun",
    population: "1.01 Crore",
    populationNum: 10100000,
    area: "53,483 km²",
    areaNum: 53483,
    districts: 13,
    urbanPopulation: "30.2%",
    forestCover: "61.0%",
    literacyRate: "78.8%",
    gdpContribution: "₹3.3 Lakh Cr",
    land: { agriculture: 14, forest: 61, built: 3, water: 2, barren: 20 },
    landUseYear: "2024-25",
    landUseSource: "Uttarakhand Space Applications Centre (USAC) / Bhulekh Uttarakhand",
    description: "'Devbhoomi', originating source of the Ganges and Yamuna rivers, sacred Himalayan shrines, and high-altitude disaster risk mitigation zones.",
    districtList: [
      "Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", 
      "Pauri Garhwal", "Pithoragarh", "Rudraprayag", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"
    ],
    mapCenter: [30.3165, 78.0322],
    zoom: 7,
    keyProjects: ["Char Dham All-Weather Road GIS Monitoring", "USAC Landslide Early Warning & Glacial Hazard Map", "Dehradun Master Plan 2041"]
  },
  "west bengal": {
    id: "west_bengal",
    name: "West Bengal",
    code: "WB",
    zone: "East",
    capital: "Kolkata",
    population: "9.13 Crore",
    populationNum: 91300000,
    area: "88,752 km²",
    areaNum: 88752,
    districts: 23,
    urbanPopulation: "31.9%",
    forestCover: "19.0%",
    literacyRate: "76.3%",
    gdpContribution: "₹17.2 Lakh Cr",
    land: { agriculture: 63, forest: 19, built: 10, water: 4, barren: 4 },
    landUseYear: "2024-25",
    landUseSource: "Department of Land and Land Reforms, West Bengal (Banglarbhumi)",
    description: "Extending from the Himalayas to the Bay of Bengal, encompassing the world's largest mangrove delta (Sundarbans) and Kolkata metropolitan hub.",
    districtList: [
      "Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Dakshin Dinajpur", "Darjeeling", 
      "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Malda", 
      "Murshidabad", "Nadia", "North 24 Parganas", "Paschim Bardhaman", "Paschim Medinipur", 
      "Purba Bardhaman", "Purba Medinipur", "Purulia", "South 24 Parganas", "Uttar Dinajpur"
    ],
    mapCenter: [22.5726, 88.3639],
    zoom: 7,
    keyProjects: ["Banglarbhumi Khatian & Plot Cadastre", "Sundarbans Biosphere Mangrove Coastal GIS", "Kolkata Metropolitan Area 2035 Urban Map"]
  },
  "delhi": {
    id: "delhi",
    name: "Delhi (NCT)",
    code: "DL",
    zone: "North",
    capital: "New Delhi",
    population: "1.68 Crore",
    populationNum: 16800000,
    area: "1,484 km²",
    areaNum: 1484,
    districts: 11,
    urbanPopulation: "97.5%",
    forestCover: "13.2%",
    literacyRate: "86.2%",
    gdpContribution: "₹10.4 Lakh Cr",
    land: { agriculture: 15, forest: 13, built: 62, water: 2, barren: 8 },
    landUseYear: "2024-25",
    landUseSource: "Delhi Development Authority (DDA) / Geospatial Delhi Ltd (GSDL)",
    description: "The National Capital Territory of India, a dense global metropolitan powerhouse with advanced 3D GIS land governance and DDA master planning.",
    districtList: [
      "Central Delhi", "East Delhi", "New Delhi", "North Delhi", "North East Delhi", 
      "North West Delhi", "Shahdara", "South Delhi", "South East Delhi", "South West Delhi", "West Delhi"
    ],
    mapCenter: [28.6139, 77.2090],
    zoom: 10,
    keyProjects: ["DDA Master Plan for Delhi 2041 (MPD-2041) GIS", "GSDL 3D Spatial Underground Utilities Portal", "Yamuna Floodplain Zone O Geofencing"]
  },
  "jammu and kashmir": {
    id: "jammu_and_kashmir",
    name: "Jammu and Kashmir",
    code: "JK",
    zone: "North",
    capital: "Srinagar (Summer) / Jammu (Winter)",
    population: "1.23 Crore",
    populationNum: 12300000,
    area: "42,241 km²",
    areaNum: 42241,
    districts: 20,
    urbanPopulation: "27.4%",
    forestCover: "52.0%",
    literacyRate: "67.2%",
    gdpContribution: "₹2.3 Lakh Cr",
    land: { agriculture: 18, forest: 52, built: 3, water: 3, barren: 24 },
    landUseYear: "2024-25",
    landUseSource: "Jammu and Kashmir Land Records Modernization / Aapki Zameen Aapki Nigrani",
    description: "Nestled in the Pir Panjal and Great Himalayan ranges, famed for Dal Lake, saffron valleys, and comprehensive digital land records.",
    districtList: [
      "Anantnag", "Bandipora", "Baramulla", "Budgam", "Doda", "Ganderbal", "Jammu", 
      "Kathua", "Kishtwar", "Kulgam", "Kupwara", "Poonch", "Pulwama", "Rajouri", 
      "Ramban", "Reasi", "Samba", "Shopian", "Srinagar", "Udhampur"
    ],
    mapCenter: [34.0837, 74.7973],
    zoom: 7,
    keyProjects: ["Aapki Zameen Aapki Nigrani Land Cadastre", "Srinagar Smart City Dal Lake Wetland Map", "Chenab Rail Bridge Geospatial Monitoring"]
  },
  "ladakh": {
    id: "ladakh",
    name: "Ladakh",
    code: "LA",
    zone: "North",
    capital: "Leh",
    population: "2.74 Lakh",
    populationNum: 274000,
    area: "59,146 km²",
    areaNum: 59146,
    districts: 2,
    urbanPopulation: "22.6%",
    forestCover: "1.5%",
    literacyRate: "77.2%",
    gdpContribution: "₹7,500 Cr",
    land: { agriculture: 1, forest: 2, built: 1, water: 2, barren: 94 },
    landUseYear: "2024-25",
    landUseSource: "Ladakh Administration Spatial Data Centre & Bhuvan",
    description: "The high-altitude cold desert plateau of trans-Himalayan India, characterized by high-altitude saline lakes (Pangong Tso) and strategic solar grid projects.",
    districtList: ["Leh", "Kargil"],
    mapCenter: [34.1526, 77.5771],
    zoom: 7,
    keyProjects: ["Pangong Tso Trans-Himalayan Eco-Zoning", "13 GW Renewable Solar-Wind Mega Grid Plan", "Ladakh Carbon Neutral Territorial GIS"]
  }
};
